-- run this from an SQL Worksheet
-- (can customized the code generated by the Python Worksheet!)
use test.public;

create or replace procedure gen_fake_rows(rownum int)
    returns Table()
    language python
    runtime_version=3.11
    packages=('faker==25.8.0','snowflake-snowpark-python==*')
    handler='main'
as $$
import snowflake.snowpark as snowpark
from faker import Faker

def main(session: snowpark.Session, rownum: int):
    f = Faker()
    output = [[f.name(), f.address(), f.city(), f.state(), f.email()]
        for _ in range(rownum)]
    df = session.create_dataframe(output,
        schema=["name", "address", "city", "state", "email"])
    df.write.mode("overwrite").save_as_table("customers_from_sp")
    df.show()
    return df
$$;

call gen_fake_rows(2000);
